#+TITLE: Guidelines to Write Final Papers
#+AUTHOR: Diogo Ferrari\\
#+AUTHOR: Department of Political Science\\
#+AUTHOR: University of California, Riverside\\
#+AUTHOR: =diogo.ferrari@ucr.edu=\\
#+DATE: 

You can find some resources at the [[https://arc.ucr.edu/writing][Undergraduate Writing Support Program]] and [[https://gwc.ucr.edu/][Graduate Writing Center]]. Here are some few tips:


1. *Include citation to back up all statements you make*\\
   /Bad/:\\
   "Many researchers use social media data to analyze public opinion and political behavior. Some findings suggest that online activism is not associated with public protests. In this paper, I will analyze the behavior of online activists...."\\
   /Good/:\\
   "Many researchers use social media data to analyze public opinion and political behavior (Madison el al., 2000, Neo, 1999, Morpheus, 1999). Some findings suggest that online activism is not associated with public protests (Trinity, 1999). In this paper, I will analyze the behavior of online activists...."
2. *Do not leave sentences vague or unexplained*\\
   /Bad/:\\
   "However, recent studies have pointed out limitations of that data (Albert, 2000). In this paper, I will present a method to overcome some of those limitations. I will..."\\
   /Good/:\\
   "However, recent studies have pointed out limitations of that data, including high noise (Albert, 2000), fake accounts, and fake statements of preferences (Bert, 2000). That create limitations in the data because high noise make it difficult to find patterns, fake accounts increase that noise, and fake statements of preferences cannot be easily identified with pure word frequences. In this paper, I will present a method to overcome some of those limitations. I will..."\\
3. *Use direct sentences and avoid long ones*\\
   /Bad/:\\
   "The conjuncture capable of transforming practices objectively co-ordinated because subordinated to partially or wholly identical objective necessities, into collective action (e .g . revolutionary action) is constituted in the dialectical relationship between, on the one hand, a habitus, understood as a system of lasting, transposable dispositions which, integrating past experiences, functions at every moment as a matrix of perceptions, appreciations, and actions and makes possible the achievement of infinitely diversified tasks, thanks to analogical transfers of schemes permitting the solution of similarly shaped problems, and thanks to the unceasing corrections of the results obtained, dialectically produced by those results, and on the other hand, an objective event which exerts its action of conditional stimulation calling for or demanding a determinate response, only on those who are disposed to constitute it as such because they are endowed with a determinate type of dispositions (which are amenable to reduplication and reinforcement by the “awakening of class consciousness”, that is, by the direct or indirect possession of a discourse capable of securing symbolic mastery of the practically mastered principles of the class habitus)."  (extracted from Bourdieu, P., 1977. /Outline of a theory of practice/. Cambridge: University Press, p. 82-83)\\
   /Good/:\\
   Some practices are objectively co-ordicated. They are so because they are partially or wholly identical to objective necessities. The conjuncture that is capable of transforming those practices into collective actions emerges in a dialectical relations between two things: habitus and an objective event that call for response. Habitus refers to a system of lasting, ... (/ok, I think you got the point/)
4. *Connect the ideas logically and smoothly using linking expressions, conjunctions, and transitional signals*\\
   /Bad/:\\
   Neo (1999) said the matrix is condemned to perish. Neo (1999) showed data from 35 matrices he found in the archive to prove his point. Morpheus (1999) said that may not be that easy and Trinity (1999) agrees. Oracle (1999) said the only thing she knows is that she knows nothing. I will focus on whatever the Architect said. \\
   /Good/:\\
   Neo (1999) said the matrix is condemned to perish and showed data from 35 matrices he found in the archive to prove his point. However, Morpheus (1999) said that may not be that easy and Trinity (1999) agrees. Oracle (1999) said the only thing she knows is that she knows nothing. Because of there is no clear agreement about matrix's destiny, I will focus on whatever the Architect said because he knows what he says, given the amount of TV channels he watches at the same time.
5. *Do not be overlook formating I: alignment/justification*\\
   /Bad/:\\
    I am the Architect. I created the Matrix. I've been waiting for you. You have many questions, and although the process has altered your consciousness, you remain irrevocably \\
    human. Ergo, some of my answers you will understand, and some of them you will not. Concordantly, while your first question \\
    may be the most pertinent, you may or may not realize it is also the most irrelevant.\\
   /Good/:\\
   I am the Architect. I created the Matrix. I've been waiting for you. You have many questions, and although the process has altered your consciousness, you remain irrevocably human. Ergo, some of my answers you will understand, and some of them you will not. Concordantly, while your first question may be the most pertinent, you may or may not realize it is also the most irrelevant.
6. *Do not be overlook formating I: citation*\\
   /Bad/:\\
   (John 2000) argues that politicians are trustworthy. Some disagree Mary (2000)\\
   /Good/:\\
   John (2000) argues that politicians are trustworthy. Some disagree (Mary, 2000)





